# Generated by Django 3.2.17 on 2023-02-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement',
            new_name='unit',
        ),
    ]
