# Generated by Django 3.2.17 on 2023-02-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_measurement_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='incredient',
            new_name='ingredient',
        ),
    ]
